### ISSUE TITLE
Usage of KafkaMessageBusOptions.DefaultConsumerThreadCount

### ISSUE THREAD

**Issue by jojopeter** [linzhiqiang/Aix.KafkaMessageBus#2]
Hi,
This is a query regarding Consumer throughput of Kafka.

I am using Aix.KafkaMessageBus package. We noticed the consumer throughput is very low and trying to optimize it. As part of this I changed the **DefaultConsumerThreadCount** from **4** to **8**. But that didn't make any difference to the consumer throughput.
Can you please let us know what is the _intention of 'DefaultConsumerThreadCount'_? Is there any other setting I can change to increate the consumer throughput?

This is the setting we have

```
      var options = new KafkaMessageBusOptions
      {
        DefaultConsumerThreadCount = 4,
        ManualCommitBatch = 10,
        ProducerConfig = new ProducerConfig
        {
          BootstrapServers = bootstrapServers,
          Acks = Acks.Leader,
          Partitioner = Partitioner.ConsistentRandom,
          SecurityProtocol = securityProtocol,
          Debug = "security"
        },
        ConsumerConfig = new ConsumerConfig
        {
          GroupId = consumerGroupId,
          BootstrapServers = bootstrapServers,
          AutoOffsetReset = AutoOffsetReset.Latest,
          EnableAutoCommit = true,
          AutoCommitIntervalMs = 5000,
          CancellationDelayMaxMs = 1000,
          SessionTimeoutMs = 100000,
          SecurityProtocol = securityProtocol,
          Debug = "security"
        }
      };
      services.AddFoundatioKafkaMessageBus(options);
```

Thanks In advance,
Jojo Peter

**Comment by linzhiqiang** [comment]
Please note the topic partition setting of Kafka,
The defaultconsumerthreadcount parameter cannot be greater than the number of partitions.

You can also set the number of threads for a topic, only for the current topic,
For a specific topic, the number of threads must not be greater than the number of partitions of the topic. The extra threads are invalid.

The following code:
               SubscribeOptions subscribeOptions = new SubscribeOptions();
                subscribeOptions.GroupId = "group";
                subscribeOptions.ConsumerThreadCount = 8;

                await _messageBus.SubscribeAsync<BusinessMessage>(async (message) =>
                {
                     //logic
                    await Task.CompletedTask;
                }, subscribeOptions, cancellationToken);

**Comment by jojopeter** [comment]
Thanks for your reply This really helps.
